version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: analytics-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend 
      - ./events.db:/app/events.db  #  Persist DB
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app             #  Enabling absolute imports

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: analytics-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
