version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: analytics-backend
    ports:
      - "8010:8000"
    volumes:
      - ./backend:/app/backend
      - ./events.db:/app/events.db
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    networks:
      - caddy-net

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
      args:
        VITE_API_URL: "/mini-analytics/api"
    container_name: analytics-frontend
    ports:
      - "3003:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=${VITE_API_URL}
    env_file:
      - .env
    networks:
      - caddy-net

networks:
  caddy-net:
    external: true
