services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: analytics-backend
    ports:
      - "8010:8000"
    volumes:
      - ./backend:/app/backend
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - DATABASE_URL=sqlite:////app/events.db
    networks:
      - caddy-net

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: analytics-frontend
    ports:
      - "3003:80"
    depends_on:
      - backend
    networks:
      - caddy-net

networks:
  caddy-net:
    external: true
