version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: analytics-backend
    ports:
      - "8010:8000"
    volumes:
      - ./backend:/app/backend
      - ./events.db:/app/events.db
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    networks:
      - caddy-net

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: analytics-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - caddy-net

networks:
  caddy-net:
    external: true
