name: 🚀 Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/github-actions-key
          chmod 600 ~/.ssh/github-actions-key
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Generate .env file
        run: echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" > .env

      - name: Upload .env to droplet
        run: |
          scp -i ~/.ssh/github-actions-key .env ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/apps/Mini-Analytics/frontend/.env

      - name: Deploy to DigitalOcean
        run: |
          ssh -i ~/.ssh/github-actions-key ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} <<EOF
            set -ex
            cd /home/apps/Mini-Analytics
            git stash push -m "Stash before deployment" || true
            git pull origin main
            VITE_API_URL=${{ secrets.VITE_API_URL }} docker compose down
            VITE_API_URL=${{ secrets.VITE_API_URL }} docker compose up -d --build
          EOF
